FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["GoodHamburger.Api/GoodHamburger.Api.csproj", "GoodHamburger.Api/"]
COPY ["GoodHamburger.Application/GoodHamburger.Application.csproj", "GoodHamburger.Application/"]
COPY ["GoodHamburger.Domain/GoodHamburger.Domain.csproj", "GoodHamburger.Domain/"]
COPY ["GoodHamburger.Infrastructure/GoodHamburger.Infrastructure.csproj", "GoodHamburger.Infrastructure/"]
RUN dotnet restore "GoodHamburger.Api/GoodHamburger.Api.csproj"
COPY . .
WORKDIR "/src/GoodHamburger.Api"
RUN dotnet build "GoodHamburger.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GoodHamburger.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GoodHamburger.Api.dll"]
